# Generated by Django 3.0.5 on 2020-08-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gun',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gun',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
